spring.application.name=gestion-sujets-service
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/gestion_sujets_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=VUFZWjIwMjZTdXBlclNlY3VyZUpXVEtleUZvckF1dGhlbnRpY2F0aW9uU3lzdGVtMTIzNDU2
jwt.expiration=86400000
utilisateur.service.url=http://localhost:8081/api